version: '{build}'
image:
- Visual Studio 2019


configuration: Debug
platform: Any CPU
  
environment:
  R_ARCH: x64
  PLATFORM: Any CPU
  BuildPLATFORM: Any CPU
  BuildConfiguration: Debug
  configuration: Debug

branches:
  only:
  - master
  - testing

# Install R for windows. 
# Borrowed from http://raw.github.com/krlmlr/r-appveyor
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: InstallR 

cache:
  - C:\RLibrary
#############

build_script:
- cmd: >-
    dotnet --info

    dotnet restore RDotNet.Tests.sln

    dotnet build --configuration Debug --no-restore  RDotNet.Tests.sln

    dotnet restore TestApps/SimpleTest/SimpleTest.csproj 

    dotnet build --configuration Debug --no-restore TestApps/SimpleTest/SimpleTest.csproj 

# Cannot run test scripts; somehow:
# The active test run was aborted. Reason: 
# Test Run Aborted.

test_script:
- cmd: >-
    dotnet run -v d --project TestApps/SimpleTest/SimpleTest.csproj 

    dotnet test -v d --blame --filter TestCharacter RDotNet.Tests/RDotNet.Tests.csproj

    dotnet test -v d --blame RDotNet.FSharp.Tests/RDotNet.FSharp.Tests.fsproj
